"""Regenerate `docs/example-export.md` from a bundled sample mission.

Run it after changing the export format:

    .venv/Scripts/python scripts/make_example_export.py
    .venv/Scripts/python scripts/make_example_export.py "26-IRB/AYVENS-021"

With no argument it uses the first mission file in `example_data/`. Two analyst
edits are applied on the way through — one narrowing the perimeter, one adding
a record the search missed — so the provenance appendix shows what a reviewed
mission looks like rather than an untouched run. Both are derived from whatever
the mission actually contains, so the script works for any sample.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from audit_front.example_backend import ExampleDataAPI, available_missions  # noqa: E402
from audit_front.exporters import session_to_markdown  # noqa: E402
from audit_front.pipeline import STAGE_KEYS, get_stage  # noqa: E402
from audit_front.runner import run_stage  # noqa: E402
from audit_front.state import MissionSession  # noqa: E402

HEADER = """<!-- Generated by scripts/make_example_export.py from a bundled sample mission.
     Two analyst edits are applied so the provenance appendix is representative.
     Do not edit by hand; re-run the script instead. -->

"""

LOCAL_RECOMMENDATION = {
    "rec_id": "REC-2024-0781",
    "title": "Formalise the KYC refresh cycle for corporate lessees",
    "mission_ref": "24-IRB/AYVENS-003",
    "risk_family": "Know Your Customer",
    "criticality": "Medium",
    "status": "Open",
    "due_date": "2026-03-31",
    "source": "analyst",
}


def build_session(mission_id: str) -> MissionSession:
    session = MissionSession(
        mission_id=mission_id, analyst="r.doe", backend_mode="example data"
    )
    client = ExampleDataAPI(latency=False)

    for key in STAGE_KEYS:
        run_stage(session, client, get_stage(key))
        payload = session.stage(key).payload

        if key == "scope_understanding":
            # A realistic intervention: the last two entities dropped as dormant.
            entities = list(payload.get("entity_filter", []))
            kept, dropped = entities[:-2], entities[-2:]
            if dropped:
                session.apply_edit(
                    key,
                    {**payload, "entity_filter": kept},
                    detail=f"changed: entity_filter (-{len(dropped)})",
                )
                session.approve(
                    key,
                    note=(
                        f"{', '.join(dropped)} dormant since 2024 — confirmed with the CFO"
                    ),
                )
            else:
                session.approve(key)
        elif key == "historical_recommendations":
            # Something the search could not see: a prior AML-only review of the
            # same entities, which the analyst knows about and adds by hand.
            entity = (kept or ["the perimeter"])[0]
            session.apply_edit(
                key,
                {
                    **payload,
                    "found": True,
                    "recommendations": [
                        *payload.get("recommendations", []),
                        {**LOCAL_RECOMMENDATION, "entity": entity},
                    ],
                },
                detail="changed: recommendations (+1), found",
            )
            session.approve(
                key, note="added from the 2024 AML-only review of the same entities"
            )
        else:
            session.approve(key)

    return session


def main() -> None:
    missions = available_missions()
    if not missions:
        raise SystemExit("no example missions found in src/audit_front/example_data/")

    mission_id = sys.argv[1] if len(sys.argv) > 1 else missions[0][0]
    known = [m for m, _ in missions]
    if mission_id not in known:
        raise SystemExit(f"unknown mission {mission_id!r}; bundled: {', '.join(known)}")

    output = ROOT / "docs" / "example-export.md"
    output.write_text(HEADER + session_to_markdown(build_session(mission_id)), encoding="utf-8")
    lines = len(output.read_text(encoding="utf-8").splitlines())
    print(f"wrote {output.relative_to(ROOT)} from {mission_id} ({lines} lines)")


if __name__ == "__main__":
    main()
