"""Regenerate `docs/example-export.md` from the bundled UK sample mission.

Run it after changing the export format:

    .venv/Scripts/python scripts/make_example_export.py

Two analyst edits are applied on the way through, so the provenance appendix
shows what a real reviewed mission looks like rather than an untouched run.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from audit_front.example_backend import AYVENS_UK, ExampleDataAPI  # noqa: E402
from audit_front.exporters import session_to_markdown  # noqa: E402
from audit_front.pipeline import STAGE_KEYS, get_stage  # noqa: E402
from audit_front.runner import run_stage  # noqa: E402
from audit_front.state import MissionSession  # noqa: E402

HEADER = """<!-- Generated by scripts/make_example_export.py from the bundled sample mission.
     Two analyst edits are applied so the provenance appendix is representative.
     Do not edit by hand; re-run the script instead. -->

"""

LOCAL_RECOMMENDATION = {
    "rec_id": "REC-2024-0781",
    "title": "Formalise the KYC refresh cycle for corporate lessees",
    "mission_ref": "24-IRB/AYVENS-003",
    "entity": "LEASEPLAN UK LIMITED",
    "risk_family": "Know Your Customer",
    "criticality": "Medium",
    "status": "Open",
    "due_date": "2026-03-31",
    "source": "analyst",
}


def build_session() -> MissionSession:
    session = MissionSession(
        mission_id=AYVENS_UK, analyst="r.doe", backend_mode="example data"
    )
    client = ExampleDataAPI(latency=False)

    for key in STAGE_KEYS:
        run_stage(session, client, get_stage(key))
        payload = session.stage(key).payload

        if key == "scope_understanding":
            # A realistic intervention: two dormant entities dropped from scope.
            kept = [e for e in payload.get("entity_filter", []) if "DIAL" not in e]
            session.apply_edit(
                key, {**payload, "entity_filter": kept}, detail="changed: entity_filter (-2)"
            )
            session.approve(
                key, note="DIAL entities dormant since 2024 — confirmed with the CFO"
            )
        elif key == "historical_recommendations":
            # The stage found nothing; the analyst knows of a prior AML-only review.
            session.apply_edit(
                key,
                {**payload, "found": True, "recommendations": [LOCAL_RECOMMENDATION]},
                detail="changed: recommendations (+1), found",
            )
            session.approve(
                key, note="added from the 2024 AML-only review of the same entities"
            )
        else:
            session.approve(key)

    return session


def main() -> None:
    output = ROOT / "docs" / "example-export.md"
    output.write_text(HEADER + session_to_markdown(build_session()), encoding="utf-8")
    lines = len(output.read_text(encoding="utf-8").splitlines())
    print(f"wrote {output.relative_to(ROOT)} ({lines} lines)")


if __name__ == "__main__":
    main()
