[theme]
base = "light"
primaryColor = "#E60028"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F5F7"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
